CREATE SEQUENCE seq_prod_type START WITH 1;
create table product_type(
type_id INTEGER GENERATED BY DEFAULT AS SEQUENCE seq_prod_type not null primary key,
type_name varchar(50) not null);


CREATE SEQUENCE seq_prod_name START WITH 1;
create table product_name(
name_id INTEGER GENERATED BY DEFAULT AS SEQUENCE seq_prod_name not null primary key,
type_id int FOREIGN KEY REFERENCES product_type(type_id) ON DELETE CASCADE,
client_id int FOREIGN KEY REFERENCES client(client_id) ON DELETE CASCADE,
product_name varchar(50) not null,
status boolean not null,
country_id int FOREIGN KEY REFERENCES country(country_id) ON DELETE CASCADE not null,
start_date DATE);


insert into product_type values(1,'share');
insert into product_type values(2,'deposit');
insert into product_type values(3,'credit');


insert into product_name values(next value for seq_prod_name,1,1,'IBM',true,1, CURDATE());
insert into product_name values(next value for seq_prod_name,1,1,'Apple',true,1, CURDATE());
insert into product_name values(next value for seq_prod_name,2,1,'Standart',true,1, CURDATE());
insert into product_name values(next value for seq_prod_name,2,1,'Maximum',true,1, CURDATE());
insert into product_name values(next value for seq_prod_name,3,1,'Minimum',true,1, CURDATE());

